import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DZ Doctors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body    className="bg-yello-50" >
        
        <div className='md:px-24 px-5 ' >
          <Header />
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
